version: '3.1'

services:
  appCart:
    image: 'cart:latest'
    build:
      context: .
    container_name: cart
    ports:
      - "8082:8082"
    depends_on:
      - dbcart
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbcart:5432/cart
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  dbcart:
    image: 'postgres'
    restart: unless-stopped
    ports:
      - "5434:5432"

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=cart
networks:
  default:
    external:
      name: challenge-network